### ISSUE TITLE
DataLoader please

### ISSUE THREAD

**Issue by lucifer-wsp** [UHN/ggql#30]
Want to support DataLoader? After all, there are many scenarios in GraphQl that are useful.

**Comment by ohler55** [comment]
Please explain in more detail. I'm not sure which DataLoader you are referring to.

**Comment by ohler55** [comment]
I've also turned on GitHub discussions which might be a better place for something like this.

**Comment by lucifer-wsp** [comment]
I actually want one ne that integrates this -> https://github.com/graphql/dataloader .

**Comment by ohler55** [comment]
Are you suggesting adding the features of the data loader to ggql or finding a way to use the existing data loader with ggql?

**Comment by lucifer-wsp** [comment]
Sorry, I think I can find a way to use gopher-dataloader directly. Thanks for your reply and i will close it,  thks again.
