### ISSUE TITLE
How to create a dynamic GraphQL schema

### ISSUE THREAD

**Issue by VojislavVlasic** [UHN/ggql#33]
Hello!
We're creating a new GraphQL API and we're researching how to improve the performance of our previous API.
We have a scenario where each user can have his own types, I was wondering if there is some way to create and load those types, based on the request headers?
Thank you!

**Comment by ohler55** [comment]
If I understand correctly there is a superset of all types and you want to limit access based on request headers. Is that correct

**Comment by VojislavVlasic** [comment]
Hello @ohler55!
Thank you for your quick response.
I've sent you an email, and I'll close this issue.
